### ISSUE TITLE
Error with configure-interfaces.py on both new server images (23.08.1) when setting ntp to 0.pool.ntp.org

### ISSUE THREAD

**Issue by patrickpritchett** [idaholab/Malcolm#247]
```
Traceback (most recent call last):
  File "/usr/local/bin/configure-interfaces.py", line 615, in <module>
    main()
  File "/usr/local/bin/configure-interfaces.py", line 388, in main
    for line in file:
  File "/usr/lib/python3.11/fileinput.py", line 251, in __next__
    line = self._readline()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/fileinput.py", line 337, in _readline
    os.rename(self._filename, self._backupfilename)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/ntp.conf' -> '/etc/ntp.conf.bak'
```

**Comment by mmguero** [comment]
Due to changes to the ntp package between debian 11 and debian 12.
